layout done
anastasiia-bgd/movies-explorer-frontend pull request #1
Opened 2023-07-08 22:06 UTC by anastasiia-bgd

2023-07-09 05:55 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* Страница с сохраненными видео не соотв. макету https://yadi.sk/d/WDDrKoR1DxcxCA
* https://yadi.sk/d/CAUFfG2sDP10sQ https://yadi.sk/d/kGBc0dFyoq_5Uw всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

главная
- 1280 https://yadi.sk/d/XmGNOpHJ_MI0Lw
- 768 https://yadi.sk/d/qdlIbZVjau1-IA https://yadi.sk/d/P60ESVGjEtJQcw https://yadi.sk/d/AcnnYXwbBQCQww https://yadi.sk/d/AcnnYXwbBQCQww
- 320 https://yadi.sk/d/WT7U8Kxnjk4mJQ https://yadi.sk/d/ZylG2Lsk6NMtYw https://yadi.sk/d/EG4lONwm6ZDY8Q https://yadi.sk/d/_9x-0aYZoi-Ytw https://yadi.sk/d/-MdAtjCJpq5zvA https://yadi.sk/d/Iuz3iWnIa2GI9g

Меню
- 320 https://yadi.sk/d/mu89hxB-mdoWOA

Фильмы
- 1280 https://yadi.sk/d/IfF5XDzalSysuA https://yadi.sk/d/fuKWFKc7j5_rFQ
- 768 https://yadi.sk/d/yIMct5oFqJAhhg https://yadi.sk/d/yOrpUGnUekgWtg
- 320 https://yadi.sk/d/_ASEptGvjN1RSQ https://yadi.sk/d/EqlH6aGAKvy7nA https://yadi.sk/d/1YCaSkFlcGRKNQ

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [ ] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

* https://anastasiia-bgd.github.io/react-mesto-auth/ - выдает ошибку 404

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

* Есть ошибки по БЭМ. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/BS9JWPySWkgOKA https://yadi.sk/d/W4ttfBrHzFU0mg В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

* https://yadi.sk/d/X5kcmchvOIlfwQ каждой секции нужен сем.заголовок, следите за иерархией
* https://yadi.sk/d/YU3f9NFaOvub-Q https://yadi.sk/d/BacoK1tciMSFsw, также на страницах регистрация и вход заголовок 1 уровня (на каждой странице следует разместить заголовок 1 уровня один). В секцию с фильмами можно секции задать ариа атрибут aria-label, т.к. по макету там он не предусмотрен.
* header__button-container, navtab - рекомендуется тег навигации nav
* https://yadi.sk/d/nvvMTLRJBA_8-w форма для одного чекбокса не оправдана, Вам следует объединить строку поиска с кнопкой и чекбокс одной формой.

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* promo__title, form__input-error элементы располагаются в потоке

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

* https://yadi.sk/d/AV-0p_fNQB0s5w при старте приложения вход по макету неосуществлен

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* На активных страницах ссылки не выделены как в макете https://yadi.sk/d/IhoLLxxU0L5whw https://yadi.sk/d/oyETvSGB9zClOw

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* На странице вход и регистрация у полей не установлены placeholder со значениями
* Для поля email следует установить соотв. тип type.
* Поля не проходят валидацию, при корректном заполнении статус ошибки остается.
* Кнопка Войти/Зарегистрироваться активна при пустых полях, также перезагружает страницу, нет валидации.

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

* https://yadi.sk/d/oUM5PgSFr7MYig изображение аватара можно урезать по ширине и оптимизировать, чтобы было легче.

## Количество баллов: 48

## Доп. Комментарии:
- Язык проекта русский ru
- https://yadi.sk/d/GoJpEn0vGl6nDA Хорошей практикой считается отображать декоративные изображения на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/
- button всем кнопкам рекомендуется описывать атрибут type

2023-07-12 08:07 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью по Вашей работе. 
Начал образовываться гор.скролл при сужении, стили частично слетели на странице с фильмами, также для того, чтобы добиться сходства по макету настоятельно рекомендую использовать плагин PixelPerfect.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* Страница с фильмами и сохраненными видео сбилась стилизация https://yadi.sk/d/t-XNziGd8dxGvg
* https://yadi.sk/d/dmjPklYOxFrshQ всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).

Сохраняются визуальные различия с макетом почти на всех страницах, рекомендуется использование плагина PixelPerfect

- https://yadi.sk/d/VweRYiQVC9guSg https://yadi.sk/d/LzrVh_aTbaTpmA https://yadi.sk/d/XmGNOpHJ_MI0Lw https://yadi.sk/d/Av47RLshHtJKhA https://yadi.sk/d/8scXNMoMbqdFoA https://yadi.sk/d/A5xbp0WsenZyCw https://yadi.sk/d/6eBMQlfzegK6tA https://yadi.sk/d/K9qYwLiWHMvk7w https://yadi.sk/d/K9qYwLiWHMvk7w https://yadi.sk/d/IvBLPUa2UkJaWw и т.д.

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/cnJjmueLv2Sp_w начал образовываться гор. скролл при сужении

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.

* (header__logged выдает ошибку по БЭМ ) Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/ZouSGnHh995jgw https://yadi.sk/d/WA5wRANhxJtsJg (иконку немного сжало) В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

* https://yadi.sk/d/YU3f9NFaOvub-Q https://yadi.sk/d/BacoK1tciMSFsw, также на страницах регистрация и вход заголовок 1 уровня (на каждой странице следует разместить заголовок 1 уровня один). В секцию с фильмами можно секции задать ариа атрибут aria-label, т.к. по макету там он не предусмотрен.
* https://yadi.sk/d/J9f8GzZNHdnXYw  селектором формы можно оформить search-form__container, чтобы чекбокс оказался внутри, также для разделения можно использовать fieldset

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* form__button-save, form__input-error элементы располагаются в потоке, можно использовать построение сетки через флекс/грид

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* На активных страницах ссылки не выделены как в макете https://yadi.sk/d/IhoLLxxU0L5whw https://yadi.sk/d/oyETvSGB9zClOw

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

* https://yadi.sk/d/zotyii60wY9OMw не установлен placeholder со значением
* https://yadi.sk/d/dIy74V_WATd9CA Для поля email следует установить соотв. тип type.
* При правильно введенных данных в поля по нажатию на кнопку следует переходить на страницу с фильмами.

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 58

2023-07-13 22:25 UTC, anastasiia-bgd commented
Добрый вечер!
Некоторые комментарии мне непонятны. Если так можно, то я ниже их напишу. У меня уже нет других вариантов)))

1. По-моему, все отображается и работает корректно. В чем тут ошибка? Если это не критично, то могу я оставить так, есть?

* селектором формы можно оформить search-form__container, чтобы чекбокс оказался внутри, также для разделения можно использовать fieldset


2. В чек-листе нет указания, что абсолютное позиционирование нельзя использовать. Почему в этом случае я не могу оставить свой вариант?

* form__button-save, form__input-error элементы располагаются в потоке, можно использовать построение сетки через флекс/грид


3. Вот это я не могу поправить и наставник тоже пока не подсказал куда смотреть. Как бы и что я не меняла, этот вертикальный скролл непобедим.

* Всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).


4. Не совсем поняла этот момент. Разве мы не на 4 этапе делаем логику?
* При правильно введенных данных в поля по нажатию на кнопку следует переходить на страницу с фильмами.

2023-07-14 08:06 UTC, Savallera commented
> Добрый вечер! Некоторые комментарии мне непонятны. Если так можно, то я ниже их напишу. У меня уже нет других вариантов)))
> 
> 1. По-моему, все отображается и работает корректно. В чем тут ошибка? Если это не критично, то могу я оставить так, есть?
> 
> * селектором формы можно оформить search-form__container, чтобы чекбокс оказался внутри, также для разделения можно использовать fieldset
> 
> 2. В чек-листе нет указания, что абсолютное позиционирование нельзя использовать. Почему в этом случае я не могу оставить свой вариант?
> 
> * form__button-save, form__input-error элементы располагаются в потоке, можно использовать построение сетки через флекс/грид
> 
> 3. Вот это я не могу поправить и наставник тоже пока не подсказал куда смотреть. Как бы и что я не меняла, этот вертикальный скролл непобедим.
> 
> * Всем страницам на уровне родительского блока следует установить высоту равную высоте вьюпорта. Также обратите внимание, что на страницах 404, профиль, регистрация и вход в макете выравнивание по вертикали идет относительно высоты вьюпорта, это значит, что на любых других устройствах оно должно центрироваться без фиксации высоты по макету не образовывая вертикальный скролл. Для реализации можно использовать технологию построения через флекс/грид, когда контент центрируется, а шапка прижата к верху, а футер к низу. Также на главной сделать липкий футер прижав хедер и растянув основной контент [Как создать липкий футер с помощью flexbox](https://webformyself.com/kak-sozdat-lipkij-futer-s-pomoshhyu-flexbox/).
> 
> 4. Не совсем поняла этот момент. Разве мы не на 4 этапе делаем логику?
> 
> * При правильно введенных данных в поля по нажатию на кнопку следует переходить на страницу с фильмами.

Здравствуйте, Анастасия!

1. Вынесла с можно лучше
2. В чек листе есть пункт `Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.`, это он. Здесь это обязательно, т.к. спан с ошибкой расположен не под полем (сломано отображение), у кнопки это поведение нежелательно, т.к. этот элемент можно разместить в потоке https://yadi.sk/d/Drd7KrObzjL18g. Не используйте большие отступы в стилях, т.к. они чаще всего создают нежелательные прокрутки, вместо этого используйте относительные, лучше выравнивание по сетке.
3. Сейчас все нормально отображается.
4. Вынесла с можно лучше

2023-07-14 08:07 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово третье ревью по Вашей работе.
Под Вашими вопросами оставила комментарии в соотв. сообщении.
Просмотрите внимательно чек-лист, уделите внимание на адаптив и соотв. с макетом, аккуратно вносите правки, чтобы не сломалось отображение на брейкпоинтах, работайте с каждым компонентом отдельно, это должно помочь в контроле за отображением по макету. Готова дать +1 итерацию, в случае вопросов обязательно обращайтесь к наставнику это сэкономит Ваши нервы и даст сил.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/h_Y_B9aluGCh-A 768 подвал
* https://yadi.sk/d/h_Y_B9aluGCh-A 320 главная
* https://yadi.sk/d/RrEj-cmhRgp3_A 320 параметры шрифта
* https://yadi.sk/d/d7NwfA1hn7zoJw 320 иконки и подвал
* https://yadi.sk/d/scOFKOZoMmkKoQ 1280 / 768 https://yadi.sk/d/xERP2kVdO5Hnrw отступ в регистрации
* https://yadi.sk/d/uIN0kH6EXhnTEw 320 поля регистрация
* https://yadi.sk/d/uIN0kH6EXhnTEw 1280 профиль / https://yadi.sk/d/ifBtZNmDBvQbaw 768 профиль, 320 также выравнивание заголовка
* https://yadi.sk/d/FVqf_naPFcuPGw 1280 отступ до кнопки
* https://yadi.sk/d/qJ9_dkaZCHhWqg 1280 отступ до секции
* https://yadi.sk/d/2OBACM6upKR08Q 768 сохраненные - подвал и отступ
* https://yadi.sk/d/iqAxquzQfDSPZw 768 фильмы - подвал и отступ
* https://yadi.sk/d/DytSf0GtCaCOHQ 320 фильмы - отступ
* https://yadi.sk/d/C38I-CV4jY_PtA 320 сохраненные - отступ

- [ ] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.

* https://yadi.sk/d/xEHkRbfxJMdBZA сохраняется образовывание гор. скролла при сужении, Вы можете просмотреть есть ли у Вас фиксированные ширины, заменить их на относительные, также перестроить макет немного заранее, если это флекс/грид, т.к. контент выпадает из блока https://yadi.sk/d/UN-hFeR4nhydcQ
* https://yadi.sk/d/s4scwpZ5Y6-kIA также обратите внимание здесь не образуется скролл, но отступ не совпадает с левым и с макетом

- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.

* https://yadi.sk/d/LzpFTgZlvX7MKg Сохраняется небольшая ошибка по БЭМ. Проверить правильность наименования классов можно также тут: https://nglazov.github.io/bem-validator-page/

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

* https://yadi.sk/d/dyp1QFEwJFQ3dA иконку не должно сжимать установите ей мин.ширину, также при смене заголовка фильма карточка тянется, этого также следует избегать.
* https://yadi.sk/d/3GRW11CTCFFGGg При сужении контента блок с карточками прижимается к левому краю, желательно центрировать относительно вьюпорта

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

* https://yadi.sk/i/oDYXKwhOpIdvMg поле ошибки располагается на абсолютной позиции, и уходит за пределы своего поля, что не соответствует макету. Вы можете удалить абсолютное позиционирование, чтобы расположить спан под полем, как в макете, а также использовать валидацию отображения ошибки, при неправильно указанных данных. https://practicum.yandex.ru/learn/web/courses/35d951a1-b62c-4a96-96ac-a8118657fad0/sprints/144303/topics/67ecb44c-7b35-47d5-9832-a5ca7229f0b3/lessons/8554dba8-f0c6-4045-8ba7-3031fddf37b1/
* form__button-save также кнопку не слеудет вырывать из потока, используйте правило построения через флекс/грид, и соотв. отступы в макете

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [ ] <!--3.38--> Работа модальных окон настроена.

* **https://yadi.sk/d/117Gg-X0xMu0xA выпадающее меню не закрывается при нажатии на крестик**

- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [ ] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.

* На страницах фильмы/сохраненные фильмы у активных ссылок в макете указана отличная толщина, т.е. когда Вы находитесь на странице с фильмами, то ссылка `Фильмы` в хедере имеет активный статус (булевый модификатор по БЭМ), толщина у нее 500, а на выпадающем меню добавляется нижнее подчеркивание. https://yadi.sk/d/cCuu_1WRfDPn8A https://yadi.sk/d/oOgRNwr_iC9eyQ

- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 60

## Дополнительно:

* https://yadi.sk/d/1e2PgvzlJXT2iQ включите в селектор формы чекбокс, т.к. он также входит в форму поиска, по нему также можно фильтровать видео

2023-07-14 13:41 UTC, anastasiia-bgd commented
Добрый день!
- Поскольку дедлайн у нас был вчера, валидацию я сделаю на следующем этапе и заодно поправлю этот комментарий. Сейчас убрала абсолютное позиционирование.

https://yadi.sk/i/oDYXKwhOpIdvMg поле ошибки располагается на абсолютной позиции, и уходит за пределы своего поля, что не соответствует макету. Вы можете удалить абсолютное позиционирование, чтобы расположить спан под полем, как в макете, а также использовать валидацию отображения ошибки, при неправильно указанных данных. https://practicum.yandex.ru/learn/web/courses/35d951a1-b62c-4a96-96ac-a8118657fad0/sprints/144303/topics/67ecb44c-7b35-47d5-9832-a5ca7229f0b3/lessons/8554dba8-f0c6-4045-8ba7-3031fddf37b1/

- Вот этот момент я тоже сделаю уже на следующем этапе, сейчас неудобно писать полноценную логику.
- https://yadi.sk/d/117Gg-X0xMu0xA выпадающее меню не закрывается при нажатии на крестик

2023-07-14 16:05 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
Обратите внимание на доп.комментарии. Вашу работу принимаю, желаю дальнейших успехов!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

* https://yadi.sk/d/h_Y_B9aluGCh-A 320 главная
* https://yadi.sk/d/RrEj-cmhRgp3_A 320 параметры шрифта
* https://yadi.sk/d/d7NwfA1hn7zoJw 320 иконки и подвал
* https://yadi.sk/d/scOFKOZoMmkKoQ 1280 / 768 https://yadi.sk/d/xERP2kVdO5Hnrw отступ в регистрации
* https://yadi.sk/d/uIN0kH6EXhnTEw 320 поля регистрация
* https://yadi.sk/d/uIN0kH6EXhnTEw 1280 профиль / https://yadi.sk/d/ifBtZNmDBvQbaw 768 профиль, 320 также выравнивание заголовка
* https://yadi.sk/d/FVqf_naPFcuPGw 1280 отступ до кнопки
* https://yadi.sk/d/qJ9_dkaZCHhWqg 1280 отступ до секции
* https://yadi.sk/d/2OBACM6upKR08Q 768 сохраненные - подвал и отступ
* https://yadi.sk/d/iqAxquzQfDSPZw 768 фильмы - подвал и отступ
* https://yadi.sk/d/DytSf0GtCaCOHQ 320 фильмы - отступ
* https://yadi.sk/d/C38I-CV4jY_PtA 320 сохраненные - отступ

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [x] <!--5.55--> Именование классов сделаны по БЭМ.
- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [x] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.
- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [x] <!--1.67--> Растровые и векторные изображения оптимизированы;

## Количество баллов: 88

## Дополнительно:

* https://yadi.sk/i/GDM49E0Drj154g при изменении контента карточка также раздвигается по ширине
* https://yadi.sk/d/1e2PgvzlJXT2iQ включите в селектор формы чекбокс, т.к. он также входит в форму поиска, по нему также можно фильтровать видео
* **https://yadi.sk/d/117Gg-X0xMu0xA выпадающее меню не закрывается при нажатии на крестик**

2023-07-23 21:06 UTC, merged